// One normalized binding list per form, whatever artifact the form's names came from.
//
//   import { loadBindings } from './bindings.mjs';
//   loadBindings('433a')  ->  from fields.433a.json   (names GENERATED from the map)
//   loadBindings('433f')  ->  from crosswalk.433f.json (names CROSSWALKED to the backbone)
//
// WHY THE TWO SOURCES CANNOT JUST BE ONE FILE
// -------------------------------------------
// 433-A was first, so every fact it held became a new name and a mechanical transform of its
// map produced all 186. Every form after it mostly reuses names that already exist, and the
// reused ones cannot be told from the new ones by any string rule — 433f_county and
// irs433_county_of_residence are one fact sharing no substring. So form one is generated and
// forms two onward are crosswalked, and that difference is permanent.
//
// What must NOT differ is the shape the fetch layer and the seeder read, because those two
// are written against each other and a round trip only proves something if both sides speak
// the same vocabulary. That is this file: it flattens both artifacts to the same rows.
//
// THE `kind` FIELD IS THE WHOLE POINT. All three of the defects that cost 433-F its round trip
// were a value arriving in the right place in the WRONG SHAPE, and each one was silent:
//
//   group   HubSpot holds a repeatable table as ONE textarea of JSON. The fill engine tests
//           Array.isArray and prints ZERO rows otherwise — no error, valid PDF, exit 0.
//   option  HubSpot's booleancheckbox stores the literal "true"/"false"; the fill engine
//           resolves against the map's option keys ("yes"/"no") and matches neither.
//   scalar  everything else, which is the only case that is safe to pass through untouched.
//
// Deciding `kind` here, once, from what the artifact recorded, is what keeps the fetch layer
// and the seeder from each re-deriving it and drifting apart.

import { readFileSync } from 'fs';
import { ENGINE_EXTRA_INPUTS } from './classification-coverage.mjs';

export function loadBindings(form) {
  if (form === '433a') return fromGeneratedFields(form);
  // 433-B(OIC) joins 433-A(OIC) here rather than falling through to fromCrosswalk: its
  // crosswalk binds a key to a classification ENTRY and names a FACT, and the property name is
  // DERIVED from the entry's category — so crosswalk.433boi.json carries no `hs_name` at all
  // and fromCrosswalk would produce 113 bindings whose hs_name is undefined. Silently, because
  // undefined is a legal thing to put in a Set of property names to request.
  if (form === '433aoi' || form === '433boi') return fromDerivedFields(form);
  return fromCrosswalk(form);
}

// FORM THREE: names were DERIVED, not crosswalked by hand and not generated by a string rule.
// crosswalk.433aoi.json binds a key to a classification ENTRY and names a fact; the name comes
// from the entry's CATEGORY, and derive-names-433aoi.mjs writes the result to fields.433aoi.json.
// So the artefact this reads has the same SHAPE as form one's and a different PROVENANCE, which
// is why it gets its own branch rather than being folded into fromGeneratedFields: that function
// infers `kind` from `source.startsWith('groups')` and from `source === 'checkboxes'`, and this
// form has a fourth construct - `check_here`, the lone box with no counterpart cell - which that
// rule would silently classify as a scalar. A lone box read as a scalar passes the value through
// untranslated, and an untranslated "true" happens to work today, which is the most dangerous
// kind of wrong: it would stop working the moment the option table changed and nothing would say
// so. Decided here, once, from what the artefact recorded.
function fromDerivedFields(form) {
  const doc = JSON.parse(readFileSync(`adapters/hubspot/fields.${form}.json`, 'utf8'));
  return doc.properties.map((p) => ({
    key: p.key,
    hs_name: p.hs_name,
    // READ OFF THE ARTEFACT, INCLUDING THE FIFTH CONSTRUCT. `groups`, `checkboxes` and
    // `check_here` are named constructs of a map. 433-B(OIC) adds `engine`: an input the engine
    // reads that the map names no cell for, and its one instance —
    // `business_income_expense_route` — is an ENUMERATION with a provisioned option set. A rule
    // keyed on the construct name alone classified it `scalar`, so the fetch layer would have
    // passed the stored value through untranslated; that happens to work today because the
    // option values and the record states are spelled identically, and it would stop working
    // the moment either moved, with no error and a valid PDF. So the discriminator is what the
    // row DECLARES: anything carrying a `map_option_by_value` is an option, whatever produced it.
    kind: p.source === 'groups' ? 'group'
      : (p.source === 'checkboxes' || p.source === 'check_here' || p.map_option_by_value) ? 'option'
        : 'scalar',
    map_option_by_value: p.map_option_by_value || null,
    row_shape: p.row_shape || null,
    aliases: [],
    classification: p.category,
    entry: p.entry,
    origin: `fields.${form}.json`,
  }));
}

// Form one: names were generated from the map, and the generator recorded which map construct
// produced each property in `source`.
function fromGeneratedFields(form) {
  const doc = JSON.parse(readFileSync(`adapters/hubspot/fields.${form}.json`, 'utf8'));
  return doc.properties.map((p) => ({
    key: p.key,
    hs_name: p.hs_name,
    kind: p.source.startsWith('groups') ? 'group' : p.source === 'checkboxes' && p.map_option_by_value ? 'option' : 'scalar',
    map_option_by_value: p.map_option_by_value || null,
    row_shape: null,
    aliases: [],
    origin: `fields.${form}.json`,
  }));
}

// Form two onward: names were crosswalked. A row carries `row_shape` if it is a serialized
// table and `map_option_by_value` if the stored value needs translating — so `kind` is read
// off the artifact rather than guessed from the name, which is what the 433f_pay_freq /
// 433f_hh_size pair would defeat (one is an option, one is a plain number, both are "freq or
// count"-looking keys).
function fromCrosswalk(form) {
  const xw = JSON.parse(readFileSync(`adapters/hubspot/crosswalk.${form}.json`, 'utf8'));
  return xw.bindings.map((r) => ({
    key: r.key,
    hs_name: r.hs_name,
    kind: Array.isArray(r.row_shape) ? 'group' : r.map_option_by_value ? 'option' : 'scalar',
    map_option_by_value: r.map_option_by_value || null,
    row_shape: r.row_shape || null,
    // Other spellings of the same input the FILL ENGINE also accepts (`household_size` for
    // 433f_hh_size, the bare `pay_freq`). The fetch layer emits the canonical `key`; the
    // seeder needs the aliases, because a hand-authored fixture predates the prefix rule and
    // reads naturally in the bare form.
    aliases: r.also_accepted_by_engine || [],
    classification: r.classification,
    origin: `crosswalk.${form}.json`,
  }));
}

// Every input key the fill engine for `form` can actually consume, from the map plus the
// inputs the engine reads through its own helpers. A key the fetch layer emits that is not in
// here never reaches the page, and the engine will not mention it.
export function consumableKeys(form, mapDoc) {
  const base = [
    ...(mapDoc.special?.composite_name_address?.from || []),
    ...Object.keys(mapDoc.map || {}),
    // `split` carries prose keys beside its definitions. The fill engines skip any entry with
    // no `parts` array, so those are not consumable inputs — filtered the same way the engine
    // skips them, and mirrored in validate-crosswalk.mjs.
    ...Object.entries(mapDoc.split || {})
      .filter(([, v]) => v && typeof v === 'object' && Array.isArray(v.parts))
      .map(([k]) => k),
    ...Object.entries(mapDoc.checkboxes || {})
      .filter(([, v]) => v && typeof v === 'object' && !Array.isArray(v) && !v.index)
      .map(([k]) => k),
    // `check_here` — the lone box with no counterpart cell, a construct 433-A(OIC) needs and
    // neither earlier map declares. Filtered the same way the fill engine skips it: an entry
    // without a string `target` is the block's own `_why` prose, not an input. Adding it here
    // is a no-op for 433-A and 433-F, whose maps have no check_here block at all — but a key
    // the fetch layer emits that is not in this set is reported as an ORPHAN, so leaving the
    // construct out would have failed all seventeen of them for the wrong reason.
    ...Object.entries(mapDoc.check_here || {})
      .filter(([, v]) => v && typeof v === 'object' && typeof v.target === 'string')
      .map(([k]) => k),
    ...Object.values(mapDoc.groups || {})
      .filter((d) => d && Array.isArray(d.slots))
      .map((d) => d.array || d.source),
    mapDoc.allowed?.national_standards_total?.input,
    ...(mapDoc.allowed?.out_of_pocket_health?.inputs || []),
  ].filter(Boolean);

  // THE ENGINE'S EXTRA INPUTS — the ones the map names only TARGETS for, or names no cell for
  // at all. IMPORTED from adapters/hubspot/classification-coverage.mjs rather than restated.
  //
  // It WAS restated here: a literal `{ '433f': [five keys] }`, a copy of the table that module
  // exports, in the file whose own header explains why the fetch layer and the seeder must not
  // each re-derive the same thing. That is the parallel-list defect guard-sweep.mjs enumerates,
  // sitting in this repo since the table was moved, and it stayed harmless only because nothing
  // had been added to the table since. 433-B(OIC)'s `business_income_expense_route` is the
  // addition that would have split them: the fetch layer would emit a key this function calls
  // unconsumable, and hs-fetch would report the route as an ORPHAN and refuse to write.
  return new Set([...base, ...(ENGINE_EXTRA_INPUTS[form] || [])]);
}
