// WHICH FIXTURE IS THIS FORM'S ACCEPTANCE FIXTURE — ASKED OF THE TREE, NEVER OF A PROMPT.
//
//   node adapters/pdf/resolve-fixture.mjs [<form>] [--role acceptance]
//
// ═══════════════════════════════════════════════════════════════════════════════════════
// WHY IT EXISTS
// ═══════════════════════════════════════════════════════════════════════════════════════
//
// `npm run gate:433boi` named `samples/433boi.slice1.sample.json`. Slice 2 had landed a week
// earlier and bound 130 more fields; the script still pointed at the slice-1 record, so the
// gate ran a three-page map against a one-page fixture and failed at step 10 with three
// unsettled exclusive sets and a coverage failure. Nothing was wrong with the map, the fixture
// or the gate. The PATH was stale, and a path in a script is a fact nobody re-derives.
//
// The same shape, one level out, is a PROMPT naming a fixture: prompt 40's §1 named
// `samples/433boi.sample.json`, which does not exist and never has.
//
// THE RULING THIS FILE IMPLEMENTS: pre-flight discovers; it is never told. A gate resolves its
// fixture from the FORM ID, and a path written down anywhere is at best a hint and at worst a
// defect. A prompt naming a fixture path is a prompt defect.
//
// ═══════════════════════════════════════════════════════════════════════════════════════
// A GLOB IS A STOP UNLESS IT DECLARES WHAT IT SWEEPS
// ═══════════════════════════════════════════════════════════════════════════════════════
//
// So this one declares it, and reports it:
//
//   directory   samples/
//   filter      a name opening with `<form>.` and ending `.json`
//   classifier  the file's OWN `_fixture.role` declaration, and nothing else
//
// THE ROLE IS DECLARED IN THE FIXTURE, NOT INFERRED FROM ITS NAME. Inference was tried on
// paper first and it cannot work: 433-F has `433f.sample.json` and `433f.multi.sample.json`
// and the acceptance one is `multi`; 433-B(OIC) has one fixture per slice and the acceptance
// one is the newest. Any naming rule that gets those right is a rule fitted to today's tree,
// which is the same object as a stale path. A candidate carrying no declaration is REPORTED as
// undeclared and is never silently promoted.
//
// SEVEN ROLES, and an eighth is a STOP. The sixth and the seventh were each added deliberately
// and the sentence is corrected rather than quietly widened: what it meant, and still means, is
// that a fixture declaring a role this file does not know is refused. Adding one is a change to
// this list, in a commit that says so.
//
// FIVE OF THE SIX ARE SINGLETONS. `record_shape` is a SET, for a structural reason given in
// full at `resolveFixtureSet` below: a record declares exactly one printed route, so one
// fixture can exercise exactly one state, and the construct's whole claim is that both states
// are checked. Its contract is a COVERAGE contract — one "holds" fixture per declared state,
// plus a "stops" fixture in each guard direction — which is stronger than exactly-one, not
// looser, and adapters/pdf/assert-record-shape.mjs is what holds it to that against the map.
//
//   acceptance   the record the gate runs saturated. EXACTLY ONE per form.
//   stress       an over-max record: more rows than the form prints, run with --saturated to
//                prove overflow is dropped and logged rather than truncated onto the page
//   negative     a record chosen to drive floors and refusals
//   production   a real record fetched from HubSpot. Never an acceptance fixture: it is a
//                portrait of one taxpayer and says nothing about coverage
//   superseded   a fixture an earlier slice's acceptance run used, kept because the run it
//                proved is in the history. It MUST name what superseded it, and that name must
//                resolve to a fixture in this directory.
//   branch       A SET, one member per side of the form's declared TWO-BRANCH PREDICATES. A
//                `when` clause puts a total line in class only on one side of a printed
//                conditional, and a record fixes each vehicle to one state — so 433-B(OIC)
//                reported "28 checked, 3 skipped" and 433-A(OIC) "49 checked, 2 skipped" ON
//                EVERY FIXTURE EITHER FORM HAD, six runs each, the same lines skipped in all of
//                them. Those lines had never been seen to agree, never mind refuse.
//                WHY A SET AND NOT ONE FILE: the acceptance record already holds one side, so a
//                single flipped fixture looks sufficient — and it is not, because the
//                acceptance record IS UNSAFE TO BREAK. Five other fixtures are generated by
//                reading it off disk, and a break held in it makes all five drift from the
//                generator they name, taking the gate down at step 3 on files nobody touched.
//                So the set carries BOTH sides and neither member is anything else's input.
//                Each member declares WHICH DIMENSION IT VARIES, and there are now TWO.
//
//                  `_fixture.branch_state`   the side of the printed two-branch PREDICATES
//                  `_fixture.subject_state`  the declared SUBJECT the record is filed under
//
//                THE SECOND DIMENSION IS AN EXTENSION AND NOT A SECOND ROLE, because it is the
//                same structural fact seen on a different axis: a record takes ONE side of each
//                printed conditional, and it is filed under ONE subject, so one fixture can
//                exercise one of each and the claim in both cases is that ALL of them are
//                reached. 433-D is the form that needed it — three of its cells exist only for
//                an individual filer and two only for a business entity, so no single record
//                can reach them all and saturation over one record is unsatisfiable by
//                construction. adapters/pdf/saturation-union.mjs is what makes the UNION the
//                unit, and it requires exactly one member per declared subject in both
//                directions: a subject with no member is a gap, and two members on one subject
//                means another declared subject is unrepresented while the count looks right.
//
//                A MEMBER DECLARING NEITHER DIMENSION IS A STOP. The fourth state is refused
//                rather than defaulted — [R-35] — because assuming a dimension would admit a
//                predicate-side fixture to the subject union, and the union would then report a
//                subject as covered by a record that never declared it.
//                A form declaring no `when` predicate and no mutually exclusive subject classes
//                needs no branch set and has none; that is a checked absence, and the authoring
//                script STOPs rather than writing an empty one.
//
// ZERO acceptance fixtures is a STOP. TWO is a STOP naming both. A `superseded_by` that names
// a file which is not here is a STOP. There is no state in which this returns a guess.

import { readFileSync, readdirSync, existsSync } from 'node:fs';

export const DIR = 'samples';
export const ROLES = ['acceptance', 'stress', 'negative', 'production', 'superseded', 'record_shape', 'branch'];

// THE ROLES THAT ARE SETS AND NOT SINGLETONS. See `resolveFixtureSet` at the foot of this file
// for the contract, and the `branch` entry above for why that role joined this set.
//
// `branch` IS A SET FOR THE SAME STRUCTURAL REASON `record_shape` IS. A record puts each printed
// conditional on ONE of its branches AND is filed under ONE subject, so one fixture can
// exercise one side of each; the claim the role exists to support is that ALL sides are
// reached — on both dimensions, since [DM-2]. One branch fixture could only ever
// prove half of it, and on 433-B(OIC) that half was not even the missing half: the acceptance
// record holds the other side and IS UNSAFE TO BREAK, because five other fixtures are generated
// by reading it off disk. So the set carries one member per side, and neither is anything else's
// input.
export const SET_ROLES = new Set(['record_shape', 'branch']);

/** Every mapped form, from the maps directory. Derived so a new form needs no edit here. */
export const MAPPED_FORMS = () =>
  readdirSync('adapters/pdf/maps').filter((f) => f.endsWith('.map.json')).map((f) => f.replace('.map.json', '')).sort();

/**
 * The declared swept set for one form, and what each candidate says it is.
 *
 * A file that will not parse is UNREADABLE and is reported as such — never skipped. A fixture
 * that cannot be read is not a fixture that is not there, and the difference is the whole of
 * [G-01]: a form whose only acceptance fixture is corrupt must not resolve to "none found".
 */
export const candidatesFor = (form) => {
  const swept = { dir: DIR, filter: `name starts with "${form}." and ends ".json"`, classifier: '_fixture.role declared in the file' };
  const files = readdirSync(DIR).filter((f) => f.startsWith(`${form}.`) && f.endsWith('.json')).sort();
  const rows = files.map((f) => {
    const path = `${DIR}/${f}`;
    let doc;
    try { doc = JSON.parse(readFileSync(path, 'utf8')); }
    catch (e) { return { path, unreadable: e.message }; }
    const fx = doc._fixture;
    if (!fx || typeof fx !== 'object') return { path, undeclared: true };
    // `recordShape` is carried out of the parse that already happened. Every consumer that
    // needs it — declaration-coverage.mjs and assert-record-shape.mjs — would otherwise re-read
    // and re-parse the same file behind its own try/catch, and one of those catches turned a
    // missing import into `null` and reported every record-shape fixture as expecting a STOP.
    // One read, one parse, one place a malformed fixture is reported.
    return { path, role: fx.role, why: fx.why, supersededBy: fx.superseded_by, declaresForm: fx.form, recordShape: fx.record_shape };
  });
  return { swept, files: files.map((f) => `${DIR}/${f}`), rows };
};

/**
 * The one fixture of a given role for a form, with everything the resolution rested on.
 * Returns { path, rows, swept, problems }. `problems` non-empty means STOP — the caller
 * reports them and exits; it never falls back to a default.
 */
export const resolveFixture = (form, role = 'acceptance') => {
  const problems = [];
  const { swept, files, rows } = candidatesFor(form);

  // A SET ROLE HAS NO SINGLETON ANSWER, AND ASKING FOR ONE IS A STOP RATHER THAN A COIN TOSS.
  // Without this, a caller asking for `branch` or `record_shape` gets the "TWO FIXTURES" refusal
  // below — which is the right outcome by accident, under a message telling the author to mark
  // one superseded. That is advice that would destroy the set.
  if (SET_ROLES.has(role))
    problems.push(`"${role}" IS A SET ROLE, not a singleton, and cannot be resolved to one fixture. `
      + `A record takes ONE side of each printed conditional and one state of each declared route, so the set carries one member per side or state and the claim is that all of them are reached. Call resolveFixtureSet(form, "${role}").`);

  for (const r of rows) if (r.unreadable)
    problems.push(`UNREADABLE   ${r.path} will not parse: ${r.unreadable}\n      A fixture that cannot be read is not a fixture that is absent. Resolution over this directory is unsafe until it parses.`);
  for (const r of rows) if (r.role && !ROLES.includes(r.role))
    problems.push(`UNKNOWN ROLE ${r.path} declares _fixture.role "${r.role}", which is not one of: ${ROLES.join(', ')}.`);
  for (const r of rows) if (r.declaresForm && r.declaresForm !== form)
    problems.push(`WRONG FORM   ${r.path} is named for ${form} and declares _fixture.form "${r.declaresForm}". One of the two is wrong and neither can be preferred silently.`);
  for (const r of rows) if (r.role === 'superseded') {
    if (!r.supersededBy) problems.push(`NO SUCCESSOR ${r.path} declares role "superseded" and names no _fixture.superseded_by. A superseded fixture must say what replaced it, or nothing distinguishes it from one somebody forgot.`);
    else if (!existsSync(r.supersededBy)) problems.push(`DEAD SUCCESSOR ${r.path} says it was superseded by ${r.supersededBy}, which is not in this tree.`);
  }

  const hits = rows.filter((r) => r.role === role);
  if (!hits.length) {
    const undeclared = rows.filter((r) => r.undeclared).map((r) => r.path);
    problems.push(
      `NO ${role.toUpperCase()} FIXTURE for ${form}. ${files.length} candidate(s) swept from ${DIR}/ (${swept.filter}):\n`
      + `      ${rows.map((r) => `${r.path} -> ${r.unreadable ? 'UNREADABLE' : (r.role || 'no _fixture.role declared')}`).join('\n      ')}\n`
      + (undeclared.length ? `      ${undeclared.length} candidate(s) declare no role. A fixture is promoted by its own declaration and never by its filename.\n` : '')
      + '      Declare _fixture: { form, role, why } in the file that should be it.');
  }
  if (hits.length > 1) {
    problems.push(
      `TWO ${role.toUpperCase()} FIXTURES for ${form}: ${hits.map((h) => h.path).join(', ')}.\n`
      + '      Exactly one fixture holds a role. Mark the older one role "superseded" with _fixture.superseded_by naming the newer.');
  }

  return { form, role, path: hits.length === 1 ? hits[0].path : null, rows, swept, files, problems };
};

/**
 * THE SIXTH ROLE, AND IT IS A SET.
 *
 * The five roles above are singletons and stay singletons: exactly one acceptance fixture, one
 * stress fixture, one negative fixture per form, and TWO is a STOP naming both. That rule is
 * what makes "the gate resolves its fixture from the form id" mean anything.
 *
 * `record_shape` cannot be a singleton and the reason is structural rather than convenient. A
 * record declares exactly ONE printed route, so one fixture can exercise exactly one state of
 * one declaration — and the whole claim of adapters/pdf/record-shape.mjs is that BOTH states
 * are checked. A form declaring two states therefore needs at least two fixtures before either
 * check has ever run, plus one per guard direction that must STOP. One fixture could only ever
 * prove half of it, and a role that admitted only one would enforce exactly that.
 *
 * SO THE CONTRACT IS A COVERAGE CONTRACT, WHICH IS STRONGER THAN "EXACTLY ONE", NOT WEAKER:
 * every fixture in the set declares `_fixture.record_shape` naming the declaration id, the
 * state, and the expectation ("holds" or "stops"); the set must hold exactly one "holds"
 * fixture per declared state of every declaration the map makes, and at least one "stops"
 * fixture in each direction. adapters/pdf/assert-record-shape.mjs is what checks that against
 * the map, and a gap there is a STOP.
 *
 * Returns { form, role, paths, rows, swept, files, problems }. `problems` non-empty means STOP.
 */
export const resolveFixtureSet = (form, role = 'record_shape') => {
  const problems = [];
  const { swept, files, rows } = candidatesFor(form);
  for (const r of rows) if (r.unreadable)
    problems.push(`UNREADABLE   ${r.path} will not parse: ${r.unreadable}
      A fixture that cannot be read is not a fixture that is absent.`);
  for (const r of rows) if (r.role && !ROLES.includes(r.role))
    problems.push(`UNKNOWN ROLE ${r.path} declares _fixture.role "${r.role}", which is not one of: ${ROLES.join(', ')}.`);
  const hits = rows.filter((r) => r.role === role);
  if (!hits.length)
    problems.push(`NO ${role.toUpperCase()} FIXTURE for ${form}. ${files.length} candidate(s) swept from ${DIR}/ (${swept.filter}). A set of size zero proves nothing and is reported as a gap, never as a set that happened to be empty.`);
  return { form, role, paths: hits.map((h) => h.path), rows, swept, files, problems };
};

/** One line per candidate, for a transcript. */
export const reportResolution = (res) => {
  console.log(`fixture resolution: ${res.form} / ${res.role}`);
  console.log(`  swept: ${res.swept.dir}/ — ${res.swept.filter}; classified by ${res.swept.classifier}`);
  for (const r of res.rows)
    console.log(`    ${r.path.padEnd(46)} ${r.unreadable ? 'UNREADABLE' : (r.role || '(no _fixture.role)')}${r.supersededBy ? ` -> ${r.supersededBy}` : ''}`);
  if (res.path) { console.log(`  resolved: ${res.path}`); return 0; }
  console.error(`FIXTURE RESOLUTION FAILED — ${res.problems.length} problem(s):`);
  res.problems.forEach((p) => console.error(`  ${p}`));
  return res.problems.length;
};

// CLI — no argument lists every mapped form, which is what pre-flight wants.
if (process.argv[1] && /resolve-fixture\.mjs$/.test(process.argv[1].replace(/\\/g, '/'))) {
  const argv = process.argv.slice(2);
  const roleAt = argv.indexOf('--role');
  const role = roleAt >= 0 ? argv[roleAt + 1] : 'acceptance';
  const forms = argv.filter((a) => !a.startsWith('--') && a !== role);
  const list = forms.length ? forms : MAPPED_FORMS();
  let bad = 0;
  for (const f of list) bad += reportResolution(resolveFixture(f, role));
  process.exit(bad ? 2 : 0);
}
