// SATURATION AS A UNION OVER A FORM'S DECLARED SUBJECT SET — [DM-2].
//
//   node adapters/pdf/saturation-union.mjs <form> [--verbose]
//
// ═══════════════════════════════════════════════════════════════════════════════════════
// WHY THE UNIT CHANGED, AND WHY ONLY FOR SOME FORMS
// ═══════════════════════════════════════════════════════════════════════════════════════
//
// Saturated mode fails on any mapped text cell an acceptance record left empty, and that rule
// is right: a count quietly coming in low is indistinguishable from the map being wrong.
//
// 433-D is the first form where ONE RECORD CANNOT SATISFY IT BY CONSTRUCTION. Five of its
// cells are subject-CONDITIONAL — three exist only for an individual filer, two only for a
// business entity — so on ANY record at least two mapped text cells are REQUIRED to be empty.
// That is a property of the printed page, not a gap in the fixture: an individual record cannot
// fill the entity cells because the page does not draw them for an individual.
//
// verify-form-coverage.mjs already states the rule correctly FOR ONE RECORD: it exempts the
// cells this record's subject requires empty, names each with the caption that made it
// conditional, and FAILS if one of them carries a value. What no tool asked, until this one, is
// the question the exemption leaves open:
//
//     is every mapped cell reached by SOME record?
//
// A cell exempted on the individual record and exempted again on the entity record is a cell
// NO record reaches — which is a map binding a cell the form never fills, and it is invisible
// to any number of single-record runs, each of which passes.
//
// ═══════════════════════════════════════════════════════════════════════════════════════
// THE UNIT IS THE UNION, AND THE SET IS THE `branch` ROLE — EXTENDED, NOT INVENTED
// ═══════════════════════════════════════════════════════════════════════════════════════
//
// adapters/pdf/resolve-fixture.mjs already carries a role that is a SET rather than a
// singleton, for exactly this structural reason: a record puts each printed conditional on ONE
// of its branches, so one fixture can exercise one side and the claim the role exists to
// support is that BOTH sides are reached. `branch` was that role for two-branch PREDICATES.
// A subject is a second dimension of the same object, so the role takes a second declared
// dimension rather than a second role being invented beside it:
//
//     _fixture.branch_state    the side of the printed PREDICATES this member takes
//     _fixture.subject_state   the declared SUBJECT this member takes
//
// A `branch` member declaring NEITHER is a STOP — the fourth state is refused rather than
// defaulted, which is [R-35] applied to the fixture register.
//
// THE UNION MEMBERS ARE THE ACCEPTANCE RECORD PLUS EVERY BRANCH MEMBER DECLARING A SUBJECT,
// because the acceptance record already holds one subject and IS UNSAFE TO BREAK — five other
// fixtures are generated by reading it off disk. The set must cover every declared subject
// EXACTLY ONCE: a subject with no member is a gap, and two members on one subject means one
// declared subject is unreached while the count looks right.
//
// ═══════════════════════════════════════════════════════════════════════════════════════
// THE FIVE FORMS THAT ARE NOT 433-D REACH THIS TOO, AND THE NO-OP IS PROVED
// ═══════════════════════════════════════════════════════════════════════════════════════
//
// [R-16]'s discipline: a check skipped on the inert form is a check nobody has run on the slice
// where the defect would already be in place. A form declaring no mutually exclusive subject
// classes has a declared subject set of size one — the empty subject — its union is the
// acceptance record alone, and the answer MUST equal what the single-record saturated run says.
// That equality is asserted rather than assumed, so a union that had stopped agreeing with the
// gate on five forms would fail here rather than on the sixth.

import { readFileSync, existsSync } from 'node:fs';
import { spawnSync } from 'node:child_process';
import { resolveFixture, resolveFixtureSet } from './resolve-fixture.mjs';
import { verifyFormCoverage } from './verify-form-coverage.mjs';
import { examined } from './examined.mjs';

const r = (p) => readFileSync(p, 'utf8');

/**
 * The declared subject set of a form, derived from its map's own subject_classes.
 *
 * DERIVED, NEVER LISTED. The set is the distinct `empty_unless` values across the conditional
 * entries — the subjects the page itself distinguishes — and a form with no conditional entry
 * has a set of size one, written as [null], which is the no-op case above rather than a
 * separate branch.
 */
export const declaredSubjects = (mapDoc) => {
  const sc = mapDoc.subject_classes;
  if (!sc) return { subjects: [null], mutuallyExclusive: false };
  const subs = [...new Set(Object.values(sc).filter((e) => e.class === 'conditional').map((e) => e.empty_unless))].filter(Boolean).sort();
  return subs.length ? { subjects: subs, mutuallyExclusive: true } : { subjects: [null], mutuallyExclusive: false };
};

/** The subject a record declares, by the same reading verify-form-coverage.mjs uses. */
const subjectOf = (form, path) => {
  let rec;
  try { rec = JSON.parse(r(path)); } catch (e) { return { unreadable: e.message }; }
  const s = String(rec[`${form}_subject`] ?? rec.subject ?? '').trim().toLowerCase();
  return { subject: s || null, fixture: rec._fixture || null };
};

/**
 * The union members for a form, with every problem that stopped the resolution.
 *
 * A PROBLEM HERE IS A STOP AND NEVER A SMALLER UNION. A union quietly missing a member is a
 * union whose residual is too large — cells reported unreached that a fixture nobody resolved
 * would have reached — and that reads as a map defect. The failure directions of a gap and of
 * a wrong map point the same way, so they must not be confusable.
 */
export const unionMembers = (form) => {
  const problems = [];
  const mapPath = `adapters/pdf/maps/${form}.map.json`;
  if (!existsSync(mapPath)) return { problems: [`no ${mapPath}`], members: [], subjects: [] };
  const mapDoc = JSON.parse(r(mapPath));
  const { subjects, mutuallyExclusive } = declaredSubjects(mapDoc);

  const acc = resolveFixture(form, 'acceptance');
  problems.push(...acc.problems);
  if (!acc.path) return { problems, members: [], subjects, mutuallyExclusive };

  const members = [{ path: acc.path, role: 'acceptance', ...subjectOf(form, acc.path) }];

  if (mutuallyExclusive) {
    const set = resolveFixtureSet(form, 'branch');
    // A form with mutually exclusive subjects and NO branch set is the gap this whole file is
    // about, and it is reported as one rather than as a union of size one that happens to leave
    // cells unreached.
    problems.push(...set.problems);
    for (const p of set.paths) {
      const s = subjectOf(form, p);
      if (s.unreadable) { problems.push(`UNREADABLE ${p}: ${s.unreadable}`); continue; }
      const fx = s.fixture || {};
      // THE EXTENDED ROLE'S CONTRACT. A branch member declares which dimension it varies, and
      // one declaring neither is refused in as many words. Defaulting it to "the subject one"
      // would put a predicate-side fixture into the subject union and make the union report a
      // subject as covered by a record that never declared it.
      const dims = ['branch_state', 'subject_state'].filter((k) => fx[k] !== undefined);
      if (!dims.length) {
        problems.push(`NO DIMENSION ${p} declares role "branch" and neither _fixture.branch_state nor _fixture.subject_state. `
          + 'The branch role carries two dimensions and a member must say which one it varies; a member declaring neither is refused rather than assumed to be either.');
        continue;
      }
      if (fx.subject_state === undefined) continue;             // a predicate-side member; not in this union
      if (fx.subject_state !== s.subject)
        problems.push(`SUBJECT DISAGREES ${p} declares _fixture.subject_state ${JSON.stringify(fx.subject_state)} and carries ${form}_subject ${JSON.stringify(s.subject)}. `
          + 'The declaration and the data are two statements about the same record and one of them is wrong; neither can be preferred silently.');
      members.push({ path: p, role: 'branch', ...s });
    }
    // EXACTLY ONE MEMBER PER DECLARED SUBJECT, both directions.
    for (const sub of subjects) {
      const hits = members.filter((m) => m.subject === sub);
      if (!hits.length) problems.push(`NO MEMBER FOR SUBJECT "${sub}" — ${form} declares cells that exist only for this subject, and no fixture in the union carries it. Every cell conditional on "${sub}" would be reported unreached, which is indistinguishable from the map binding a cell the form never fills.`);
      if (hits.length > 1) problems.push(`TWO MEMBERS FOR SUBJECT "${sub}": ${hits.map((h) => h.path).join(', ')}. The union would look complete while another declared subject went unrepresented.`);
    }
    for (const m of members) if (m.subject && !subjects.includes(m.subject))
      problems.push(`MEMBER ON AN UNDECLARED SUBJECT ${m.path} carries ${form}_subject ${JSON.stringify(m.subject)} and the map declares no cell conditional on it (${subjects.join(', ')}). Either the map or the fixture is describing a subject the other does not know about.`);
  }
  return { problems, members, subjects, mutuallyExclusive, mapDoc };
};

/** Fill one member and read its coverage back. The fill engine is the gate's, unchanged. */
const coverageFor = async (form, member) => {
  const rec = JSON.parse(r(member.path));
  const out = `adapters/pdf/out/${form}_filled_${rec.intake_id || 'sample'}.pdf`;
  // maxBuffer RAISED FROM THE 1MB DEFAULT, and it matters because this call is NESTED: when
  // assert-examined.mjs spawns this tool it captures its output too, and a fill engine that
  // overran the default here would be killed with ENOBUFS and reported as a fill failure —
  // a true-sounding message about the wrong cause. The outer spawn in assert-examined.mjs
  // already carries 64MB for the same reason.
  const run = spawnSync(process.execPath, [`adapters/pdf/fill-${form}.mjs`, member.path, '--saturated'], { encoding: 'utf8', maxBuffer: 64 * 1024 * 1024 });
  if (run.status !== 0) return { member, failed: `fill-${form}.mjs exited ${run.status}`, stderr: (run.stderr || '').slice(-600) };
  if (!existsSync(out)) return { member, failed: `fill reported success and ${out} does not exist` };
  const cov = await verifyFormCoverage(form, out, { saturated: true, recordPath: member.path });
  return { member, out, cov };
};

export const runSaturationUnion = async (form) => {
  // THE CANARY RUNS BEFORE ANYTHING IS TRUSTED. A union that cannot intersect reports an
  // empty residual, which is the same thing a healthy tree reports.
  const canary = runUnionCanary();
  const { problems, members, subjects, mutuallyExclusive } = unionMembers(form);
  if (!canary.ok) problems.unshift(`CANARY DEAD — the planted cell came back as ${JSON.stringify(canary.planted)} (expected "b") and the conforming pair yielded ${canary.conforming} (expected 0).
      ${canary.why}
      Every "0 empty on EVERY member" below is meaningless. STOP.`);
  if (problems.length) return { form, problems, members, subjects, mutuallyExclusive, canary, runs: [] };

  const runs = [];
  for (const m of members) runs.push(await coverageFor(form, m));
  const failed = runs.filter((x) => x.failed);
  if (failed.length)
    return { form, problems: failed.map((x) => `${x.member.path}: ${x.failed}${x.stderr ? '\n      ' + x.stderr.split('\n').slice(-4).join('\n      ') : ''}`), members, subjects, mutuallyExclusive, runs };

  // THE UNION. A cell is REACHED if any member fed it; the residual is the set empty on EVERY
  // member, and that is the figure the saturation claim is now made over.
  const nameOf = (e) => (typeof e === 'string' ? e : e.name);
  const emptyPer = runs.map((x) => new Set((x.cov.bucket.text_empty || []).map(nameOf)));
  const requiredPer = runs.map((x) => new Set((x.cov.bucket.cond_required_empty || []).map(nameOf)));
  const everyCellEmptySomewhere = new Set([...emptyPer, ...requiredPer].flatMap((s) => [...s]));
  const unreachedByAll = [...everyCellEmptySomewhere].filter((cell) =>
    runs.every((x, i) => emptyPer[i].has(cell) || requiredPer[i].has(cell))).sort();

  const reachedBySome = [...everyCellEmptySomewhere].filter((c) => !unreachedByAll.includes(c)).sort();

  // A GUARD REPORTS HOW MANY ITEMS IT EXAMINED, AND THE POPULATION IS THE MAPPED TEXT CELLS
  // THE UNION READ — never the residual, which is zero on a healthy tree and would be a count
  // of nothing. A union over an empty cell set reports the same clean verdict as a union over
  // 168, and this line is what separates them.
  const population = new Set(runs.flatMap((x) => [
    ...(x.cov.bucket.text_written || []), ...(x.cov.bucket.text_empty || []), ...(x.cov.bucket.cond_required_empty || []),
  ].map(nameOf)));
  examined('saturation-union', form, population.size, 'mapped-text-cells');

  const out = { form, problems: [], members, subjects, mutuallyExclusive, canary, runs, unreachedByAll, reachedBySome, population: population.size };

  // THE NO-OP PROOF, ON EVERY FORM THAT IS NOT 433-D. With one member the union is that member,
  // so the residual must be exactly what the single record left empty — and the gate has
  // already failed if that is non-empty. Asserted rather than assumed: a union that had stopped
  // agreeing with the single-record answer would be wrong on five forms silently.
  if (!mutuallyExclusive) {
    const single = [...emptyPer[0]].sort();
    out.noopProof = { members: members.length, singleEmpty: single.length, unionResidual: unreachedByAll.length };
    if (members.length !== 1) out.problems.push(`NO-OP BROKEN — ${form} declares no mutually exclusive subject classes and the union resolved ${members.length} member(s). With one subject the union must be the acceptance record alone.`);
    if (single.length !== unreachedByAll.length || single.some((c) => !unreachedByAll.includes(c)))
      out.problems.push(`NO-OP BROKEN — ${form}'s union residual (${unreachedByAll.length}) is not the single record's empty set (${single.length}). With one member the two are the same set by construction, so they have diverged in the code rather than in the tree.`);
  }

  if (unreachedByAll.length)
    out.problems.push(`${unreachedByAll.length} mapped text cell(s) are empty on EVERY member of the union: ${unreachedByAll.join(', ')}.\n`
      + `      No record this form admits reaches them. A cell exempted on one subject and exempted again on the other is a cell NOTHING fills, and it passes every single-record saturated run.`);
  return out;
};

// ═══════════════════════════════════════════════════════════════════════════════════════
// THE CANARY, AND WHY THIS CONSTRUCT NEEDS ONE MORE THAN MOST
// ═══════════════════════════════════════════════════════════════════════════════════════
//
// The union arithmetic has exactly one interesting output — the set of cells empty on EVERY
// member — and on a healthy tree that set is EMPTY. So the live run prints 0 whether the
// arithmetic works or not, which is the vacuous-guard shape in the tool written to close a
// coverage gap. Nothing on the real tree distinguishes the two.
//
// AND IT CANNOT BE PLANTED FROM THE MAP, which is worth stating rather than leaving as a
// missing firing proof. To make a cell unreached by every member on a two-subject form, it must
// be required empty on BOTH — and a cell carries ONE `empty_unless`, so the only way to reach
// that state through the map is a THIRD declared subject. A third subject with no fixture is
// refused earlier and louder, by `NO MEMBER FOR SUBJECT`, and the run returns before the union
// is computed. That is the right precedence and it is also why the branch below has no
// map-level plant: the engine refuses the input that would produce it.
//
// This is the in-process class [R-28] declares — a detector planting a defect inside its own
// process has no multi-step run, so "at the step" has no referent, and what stands in its place
// is the planted defect found BY NAME with a conforming input still accepted. Both are here,
// and the SECOND direction is the one that matters: a union that reported everything unreached
// would fail the conforming case, and a union that reported nothing would fail the planted one.
export const runUnionCanary = () => {
  const cell = (n) => ({ name: n });
  const mk = (written, empty, req) => ({ cov: { bucket: { text_written: written.map(cell), text_empty: empty.map(cell), cond_required_empty: req.map(cell) } } });
  // Two synthetic members. `a` is written by member 1 and required-empty on member 2; `b` is
  // required empty on BOTH, which is the state no map can express and every map must be
  // checkable for.
  const runs = [mk(['a'], [], ['b']), mk([], ['a'], ['b'])];
  const nameOf = (e) => (typeof e === 'string' ? e : e.name);
  const union = (rs) => {
    const emptyPer = rs.map((x) => new Set((x.cov.bucket.text_empty || []).map(nameOf)));
    const reqPer = rs.map((x) => new Set((x.cov.bucket.cond_required_empty || []).map(nameOf)));
    const all = new Set([...emptyPer, ...reqPer].flatMap((s) => [...s]));
    return [...all].filter((c) => rs.every((x, i) => emptyPer[i].has(c) || reqPer[i].has(c))).sort();
  };
  const planted = union(runs);
  // The conforming case: the same two members, with `b` now fed by member 2.
  const conforming = union([mk(['a'], [], ['b']), mk(['b'], ['a'], [])]);
  return {
    ok: planted.length === 1 && planted[0] === 'b' && conforming.length === 0,
    planted: planted.join(',') || 'none', conforming: conforming.length,
    why: 'a cell required empty on BOTH synthetic members must be found BY NAME, and the same two members with that cell fed by one of them must yield nothing — a union that intersected nothing would pass the first test by reporting everything, and one that intersected everything would pass the second by reporting nothing',
  };
};

export const reportSaturationUnion = (s, { verbose = false } = {}) => {
  if (s.canary) console.log(`    canary: ${s.canary.ok ? 'holds' : 'DEAD'} (planted ${s.canary.planted}, conforming ${s.canary.conforming})`);
  console.log(`saturation union: ${s.form} — declared subject set { ${s.subjects.map((x) => x ?? '(none)').join(', ')} }, ${s.mutuallyExclusive ? 'MUTUALLY EXCLUSIVE' : 'not mutually exclusive'}`);
  for (const m of s.members) console.log(`    member  ${m.path.padEnd(40)} role=${m.role} subject=${m.subject ?? '(none)'}`);
  if (s.runs.length && !s.runs.some((x) => x.failed)) {
    for (const x of s.runs) {
      const b = x.cov.bucket;
      console.log(`    ${x.member.path.split('/').pop().padEnd(30)} text_written ${String((b.text_written || []).length).padStart(3)}  text_empty ${String((b.text_empty || []).length).padStart(3)}  required_empty ${String((b.cond_required_empty || []).length).padStart(3)}`);
    }
    console.log(`    union over ${s.population} mapped text cell(s): ${s.reachedBySome.length} empty on SOME member and reached by another; ${s.unreachedByAll.length} empty on EVERY member.`);
    if (verbose && s.reachedBySome.length) console.log(`      reached by some: ${s.reachedBySome.join(', ')}`);
  }
  if (s.noopProof) console.log(`    no-op proof: ${s.noopProof.members} member, single-record empty ${s.noopProof.singleEmpty}, union residual ${s.noopProof.unionResidual} — equal, as one member requires.`);
  if (!s.problems.length) {
    console.log(`OK — every mapped text cell on ${s.form} is fed by SOME member of its declared subject set, and each member still refuses a value in a cell its own subject requires empty.`);
    return 0;
  }
  console.error(`SATURATION UNION — ${s.problems.length} problem(s):`);
  s.problems.forEach((p) => console.error(`  ${p}`));
  return s.problems.length;
};

// CLI — no argument runs every mapped form, which is what a sweep wants.
if (process.argv[1] && /saturation-union\.mjs$/.test(process.argv[1].replace(/\\/g, '/'))) {
  const argv = process.argv.slice(2);
  const verbose = argv.includes('--verbose');
  const forms = argv.filter((a) => !a.startsWith('--'));
  const { MAPPED_FORMS } = await import('./resolve-fixture.mjs');
  let bad = 0;
  for (const f of (forms.length ? forms : MAPPED_FORMS())) bad += reportSaturationUnion(await runSaturationUnion(f), { verbose });
  process.exit(bad ? 2 : 0);
}
